function tasks = tm_get_tasks()
%% tm_get_tasks
% Return a cell array with all tomoman tasks.
%
% WW 06-2022


%% Task list
tasks = {'pipeline';...     % Always leave pipelien as first
         'import';...
         'relion_motioncorr';...
         'motioncor2';...
         'clean_stacks';...
         'dosefilter';...
         'aretomo';...
         'ctffind4';...
         'tiltctf';...
         'imod_preprocess';...
         'novactf';...
         };
     
     
end